### ISSUE TITLE
编辑超链接

### ISSUE THREAD

**Issue by wangfufu** [YeDaxia/Android-YRichEditor#1]
请问怎么编辑超链接呀？谢谢

**Comment by YeDaxia** [comment]
选中文字 点击 Link。

**Comment by wangfufu** [comment]
你好 如果想要点击链接文字的时候弹出修改可以实现吗

**Comment by wangfufu** [comment]
还有一个bug就是当图片有center标签包裹的时候 没有解析出图片地址  而是显示出了源代码

**Comment by YeDaxia** [comment]
这只是个示例工程，关注度不高，抱歉目前没有额外的精力进行维护，你可以自行基于它的基础进行修改。
